name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building App Image
      run: docker build . --file Dockerfile --tag app:$(date +%s)
      working-directory: backend/app
      
    - name: Building Mongo Image
      run: docker build . --file Dockerfile --tag mongo:$(date +%s)
      working-directory: backend/mongo
